### ISSUE TITLE
display local file 

### ISSUE THREAD

**Issue by jedierikb** [seikichi/tiff.js#11]
Can you display a TIFF from a dataTransfer object (e.g. from a drag & drop)?

**Comment by sohaibjaved44** [comment]
I'm getting issue with local file load. 
the provided code doesn't allow me to load file from local machine it needs to be a remote url.

**Comment by seikichi** [comment]
Sorry for tooooooooooooo late reply.  I add drag & drop example ( http://seikichi.github.io/tiff.js/upload.html ). Pleasae see it!
