### ISSUE TITLE
Demo attempts to load jquery over HTTP when loaded over HTTPS

### ISSUE THREAD

**Issue by mohag** [seikichi/tiff.js#12]
When attempting to view the demo via HTTPS in chrome, it fails to load due to jquery being requested over HTTP.

Error in console: (Chrome)

```
Mixed Content: The page at 'https://seikichi.github.io/tiff.js/basic.html' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-1.10.1.min.js'. This request has been blocked; the content must be served over HTTPS.
```

This can be corrected by using [protocol relative URLs](http://www.paulirish.com/2010/the-protocol-relative-url/) or by always using an HTTPS version of jquery.

**Comment by seikichi** [comment]
Thanks! (fixed by https://github.com/seikichi/tiff.js/commit/ea8c9da0bbf49f3d7c0cd091063ab32dc4c17f2c )
