### ISSUE TITLE
alternative to tiff.js

### ISSUE THREAD

**Issue by photopea** [seikichi/tiff.js#22]
Hi guys,

I am developing [Photopea editor](//www.Photopea.com) and I needed a client-side TIFF parser.

Since tiff.js is 1.5 MB, I made my own TIFF parser [UTIF.js](https://github.com/photopea/UTIF.js), which is just 17 kB and has almost the same capabilities. If you want to extend it or play around, you don't need Emscripten or any other native apps.

**Comment by seikichi** [comment]
Hi @photopea (sorry for toooooo late reply) , thank you for nice information! 

I added **Alternatives** section in [README.md](https://github.com/seikichi/tiff.js#alternatives) and add your library. Thanks! (pure javascript tiff parser is very nice, because tiff.js is large ... :-p )
