### ISSUE TITLE
publish to npm (or other package manager?)

### ISSUE THREAD

**Issue by jfoo1984** [seikichi/tiff.js#25]
I couldn't find it on npm, but was wondering if it might be possible to have this published on npm?  I think there's a fork of this repo published on bower, but it doesn't appear to have any of the more recent updates.

**Comment by seikichi** [comment]
Hi @jfoo1984 

Sorry for late reply. I updated the library and release it to npm ( https://www.npmjs.com/package/tiff.js ). Pleaase try it!

For more information (installation, example), please see the [README.md](https://github.com/seikichi/tiff.js/blob/master/README.md)

**Comment by jfoo1984** [comment]
thanks!
