### ISSUE TITLE
TIFFReadDirectory: Warning, Unknown field with tag 33550 (0x830e) encountered

### ISSUE THREAD

**Issue by ltinerary** [seikichi/tiff.js#62]
when I load a *.tif file,I got this warning:
```bash
TIFFReadDirectory: Warning, Unknown field with tag 33550 (0x830e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 33922 (0x8482) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 34735 (0x87af) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 34737 (0x87b1) encountered.
```

**Comment by johnthad** [comment]
These sort of errors are right out of the underlying LIBTIFF (written in C). You'll commonly see them for vendor tags outside the TIFF specification. I've never seen a time when I can't ignore them.

**Comment by ltinerary** [comment]
> These sort of errors are right out of the underlying LIBTIFF (written in C). You'll commonly see them for vendor tags outside the TIFF specification. I've never seen a time when I can't ignore them.
 
Thanks.
I changed a other *.tif file,and the file can show in the web browser also I stiil found this warning.
I don't understand why.
