### ISSUE TITLE
Cannot read property 'slice' of null on React Project

### ISSUE THREAD

**Issue by feiaaa** [seikichi/tiff.js#66]
hi, I used this plugin to show tiff formatted images. It works on the HTML project which combines with css，jquery and tiff.js .but it doesn't work on the React project.

the tiff image comes from the demo. url="http://seikichi.github.io/tiff.js/images/minisblack-1c-16b.tiff";

```
var Tiff = require('tiff.js');
dispatch({
      type: 'tif/queryTif',
      payload:{},
      callback:(buffer)=>{     
        // buffer is arrayType format; //
         var tiff = new Tiff({buffer: buffer}); // error here
         var canvas = tiff.toCanvas();
         var width = tiff.width();
         var height = tiff.height(); 
         console.log(width,height);
      }
    })
```

```
export async function queryTif() {
  return fetch('/tiff.js/images/minisblack-1c-16b.tiff',{ // I used a proxy here so the address was spliced
    method: 'GET',
    responseType:"arrayBuffer",
  })
  .then(res=>{
    return res.arrayBuffer()
  });
}
```

the buffer result  I got is:
```
ArrayBuffer(47733)byteLength: (...)[[Prototype]]: ArrayBuffer[[Int8Array]]: Int8Array(47733)[[Uint8Array]]: Uint8Array(47733)[[ArrayBufferByteLength]]: 47733[[ArrayBufferData]]: "0x002a01638000" 
```

error code is here:
```
Error: TypeError: Cannot read properties of null (reading 'slice')
```

**Comment by johnthad** [comment]
Unless you're running this code through a bundler, `require()` is not supported in a browser.

**Comment by feiaaa** [comment]
It was run in Webpack. 
I open the node_modules folder, formatted and read the [tiff.js](https://raw.githubusercontent.com/seikichi/tiff.js/master/tiff.js),
then I found the error comes from 
```
var sourceRegex = /^function\s*\(([^)]*)\)\s*{\s*([^*]*?)[\s;]*(?:return\s*(.*?)[;\s]*)?}$/;
        function parseJSFunc(jsfunc) {
            var parsed = (jsfunc.toString().match(sourceRegex)||[]).slice(1);
            return {
                arguments: parsed[0],
                body: parsed[1],
                returnValue: parsed[2]
            }
        }
```
I got
```
jsfunc.toString(): function stackSave()
```
so the ```parsed``` return ```null```, then throw the error.

I rewrote the ```parsed``` below
```
var parsed = (jsfunc.toString().match(sourceRegex)||[]).slice(1);
```
Finally, it works.

**Comment by johnthad** [comment]
There is an all-JS TIFF library at https://github.com/photopea/UTIF.js. It is much smaller, is actively maintained, and supports ES5 `import`. The most current version is often _not_ on npm, but you may download and keep your own copy locally. I've found it reliable.

**Comment by WHmuse** [comment]
> 

你这个是改了源码么  我咋没在代码里看到这个

**Comment by feiaaa** [comment]
> > 
> 
> 你这个是改了源码么 我咋没在代码里看到这个
search from [demo](http://seikichi.github.io/tiff.js/images/minisblack-1c-16b.tiff)
and then replace `function parseJSFunc(jsfunc){var parsed=jsfunc.toString().match(sourceRegex).slice(1)`
